steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/supercloud-monorepo/supercloud-console', 
    '-f', 'apps/console/Dockerfile', 
    '--build-arg', 'NEXT_PUBLIC_API_URL=${_API_URL}',
    '.'
  ]
images:
- 'gcr.io/supercloud-monorepo/supercloud-console'
